# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86e97b07ae0ab048a5b994c6b2adf626f4e107f04d7492698ac7e1898de2875f6788f21d71302f4906407dec281eba6043143f1f951a6332cc2af5340766dc95

test:
  secret_key_base: 568b74903357008723ffa3174cc93d96e685be32099fe254f5536977543ac54b0d1cc5727c0e5d337f5b7ed7c05ba2347fad341fa9faee13039cbc6b91b4b45f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
